
exports_files([
	"Intents.mobileprovision",
	"NotificationContent.mobileprovision",
	"NotificationService.mobileprovision",
	"Share.mobileprovision",
	"Telegram.mobileprovision",
	"Widget.mobileprovision",
	"BroadcastUpload.mobileprovision"
])
